
server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./testdb;MODE=MariaDB;AUTO_SERVER=TRUE;NON_KEYWORDS=USER,SHOW,MODE,CODE
    username: localDB
    password: localDB

  sql:
    init:
      mode: always

  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  redis:
    host: meaningless-dummy-string
    port: 1234
