name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: resume_editor/resumeeditorbackend
          stage: main
          yaml: |
            name: resumeeditorbackend
            app: java@17
            options:
              ports: "8088"
              env:
                - name: DB_URL
                  value: db_url
                - name: DB_USERNAME
                  value: db_username
                - name: DB_PASSWORD
                  value: db_password
                - name: DB_HOST
                  value: db_host
                - name: DB_PORT
                  value: db_port
                - name: GPT_API_KEY
                  value: gpt_api_key
                - name: REDIS_HOST
                  value: redis_host
                - name: REDIS_PORT
                  value: redis_port
                - name: QDRANT_GRPC_HOST
                  value: qdrant_grpc_host
                - name : QDRANT_API_KEY
                  value: qdrant_api_key
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
